version: 2
updates:
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    groups:
      dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependabot"
    groups:
      dependencies:
        patterns:
          - "*"
