// <auto-generated/>
#nullable enable

namespace Omnius.Core.Net.Connections.Secure
{
    public enum OmniSecureConnectionType : byte
    {
        Unknown = 0,
        Connected = 1,
        Accepted = 2,
    }
    public enum OmniSecureConnectionVersion : byte
    {
        Unknown = 0,
        Version1 = 1,
    }
}
