// <auto-generated/>
#nullable enable

namespace Omnius.Core.Storages.Tests.Internal;

internal sealed partial class TestMessage : global::Omnius.Core.RocketPack.RocketMessage<global::Omnius.Core.Storages.Tests.Internal.TestMessage>
{
    static TestMessage()
    {
        Formatter = new ___CustomSerializer();
        Empty = new global::Omnius.Core.Storages.Tests.Internal.TestMessage(global::Omnius.Core.RocketPack.Utf8String.Empty);
    }

    private readonly global::System.Lazy<int> ___hashCode;

    public static readonly int MaxCommentLength = 2147483647;

    public TestMessage(global::Omnius.Core.RocketPack.Utf8String comment)
    {
        if (comment is null) throw new global::System.ArgumentNullException("comment");
        if (comment.Length > 2147483647) throw new global::System.ArgumentOutOfRangeException("comment");

        this.Comment = comment;

        ___hashCode = new global::System.Lazy<int>(() =>
        {
            var ___h = new global::System.HashCode();
            if (!comment.IsEmpty) ___h.Add(comment.GetHashCode());
            return ___h.ToHashCode();
        });
    }

    public global::Omnius.Core.RocketPack.Utf8String Comment { get; }

    public static bool operator ==(global::Omnius.Core.Storages.Tests.Internal.TestMessage? left, global::Omnius.Core.Storages.Tests.Internal.TestMessage? right)
    {
        return (right is null) ? (left is null) : right.Equals(left);
    }
    public static bool operator !=(global::Omnius.Core.Storages.Tests.Internal.TestMessage? left, global::Omnius.Core.Storages.Tests.Internal.TestMessage? right)
    {
        return !(left == right);
    }
    public override bool Equals(object? other)
    {
        if (other is not global::Omnius.Core.Storages.Tests.Internal.TestMessage) return false;
        return this.Equals((global::Omnius.Core.Storages.Tests.Internal.TestMessage)other);
    }
    public override bool Equals(global::Omnius.Core.Storages.Tests.Internal.TestMessage? target)
    {
        if (target is null) return false;
        if (object.ReferenceEquals(this, target)) return true;
        if (this.Comment != target.Comment) return false;

        return true;
    }
    public override int GetHashCode() => ___hashCode.Value;

    private sealed class ___CustomSerializer : global::Omnius.Core.RocketPack.IRocketMessageSerializer<global::Omnius.Core.Storages.Tests.Internal.TestMessage>
    {
        public void Serialize(ref global::Omnius.Core.RocketPack.RocketMessageWriter w, scoped in global::Omnius.Core.Storages.Tests.Internal.TestMessage value, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            w.Put(value.Comment);
        }
        public global::Omnius.Core.Storages.Tests.Internal.TestMessage Deserialize(ref global::Omnius.Core.RocketPack.RocketMessageReader r, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            global::Omnius.Core.RocketPack.Utf8String p_comment = global::Omnius.Core.RocketPack.Utf8String.Empty;

            {
                p_comment = r.GetString(2147483647);
            }
            return new global::Omnius.Core.Storages.Tests.Internal.TestMessage(p_comment);
        }
    }
}
