// <auto-generated/>
#nullable enable

namespace Core.Net.Connections.Multiplexer;

public enum OmniConnectionMultiplexerVersion : byte
{
    Unknown = 0,
    Version1 = 1,
}
public enum OmniConnectionMultiplexerType : byte
{
    Unknown = 0,
    Connected = 1,
    Accepted = 2,
}
