// <auto-generated/>
#nullable enable

namespace Omnius.Core.RocketPack.Tests.Internal;

internal enum Enum1 : sbyte
{
    Yes = 0,
    No = 1,
}
internal enum Enum2 : short
{
    Yes = 0,
    No = 1,
}
internal enum Enum3 : int
{
    Yes = 0,
    No = 1,
}
internal enum Enum4 : long
{
    Yes = 0,
    No = 1,
}
internal enum Enum5 : byte
{
    Yes = 0,
    No = 1,
}
internal enum Enum6 : ushort
{
    Yes = 0,
    No = 1,
}
internal enum Enum7 : uint
{
    Yes = 0,
    No = 1,
}
internal enum Enum8 : ulong
{
    Yes = 0,
    No = 1,
}
internal sealed partial class StructElement : global::Omnius.Core.RocketPack.RocketMessage<global::Omnius.Core.RocketPack.Tests.Internal.StructElement>
{
    static StructElement()
    {
        Formatter = new ___CustomSerializer();
        Empty = new global::Omnius.Core.RocketPack.Tests.Internal.StructElement(false);
    }

    private readonly global::System.Lazy<int> ___hashCode;

    public StructElement(bool x0)
    {
        this.X0 = x0;

        ___hashCode = new global::System.Lazy<int>(() =>
        {
            var ___h = new global::System.HashCode();
            if (x0 != default) ___h.Add(x0.GetHashCode());
            return ___h.ToHashCode();
        });
    }

    public bool X0 { get; }

    public static bool operator ==(global::Omnius.Core.RocketPack.Tests.Internal.StructElement? left, global::Omnius.Core.RocketPack.Tests.Internal.StructElement? right)
    {
        return (right is null) ? (left is null) : right.Equals(left);
    }
    public static bool operator !=(global::Omnius.Core.RocketPack.Tests.Internal.StructElement? left, global::Omnius.Core.RocketPack.Tests.Internal.StructElement? right)
    {
        return !(left == right);
    }
    public override bool Equals(object? other)
    {
        if (other is not global::Omnius.Core.RocketPack.Tests.Internal.StructElement) return false;
        return this.Equals((global::Omnius.Core.RocketPack.Tests.Internal.StructElement)other);
    }
    public override bool Equals(global::Omnius.Core.RocketPack.Tests.Internal.StructElement? target)
    {
        if (target is null) return false;
        if (object.ReferenceEquals(this, target)) return true;
        if (this.X0 != target.X0) return false;

        return true;
    }
    public override int GetHashCode() => ___hashCode.Value;

    private sealed class ___CustomSerializer : global::Omnius.Core.RocketPack.IRocketMessageSerializer<global::Omnius.Core.RocketPack.Tests.Internal.StructElement>
    {
        public void Serialize(ref global::Omnius.Core.RocketPack.RocketMessageWriter w, scoped in global::Omnius.Core.RocketPack.Tests.Internal.StructElement value, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            w.Put(value.X0);
        }
        public global::Omnius.Core.RocketPack.Tests.Internal.StructElement Deserialize(ref global::Omnius.Core.RocketPack.RocketMessageReader r, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            bool p_x0 = false;

            {
                p_x0 = r.GetBoolean();
            }
            return new global::Omnius.Core.RocketPack.Tests.Internal.StructElement(p_x0);
        }
    }
}
internal sealed partial class MessageElement : global::Omnius.Core.RocketPack.RocketMessage<global::Omnius.Core.RocketPack.Tests.Internal.MessageElement>
{
    static MessageElement()
    {
        Formatter = new ___CustomSerializer();
        Empty = new global::Omnius.Core.RocketPack.Tests.Internal.MessageElement(false);
    }

    private readonly global::System.Lazy<int> ___hashCode;

    public MessageElement(bool x0)
    {
        this.X0 = x0;

        ___hashCode = new global::System.Lazy<int>(() =>
        {
            var ___h = new global::System.HashCode();
            if (x0 != default) ___h.Add(x0.GetHashCode());
            return ___h.ToHashCode();
        });
    }

    public bool X0 { get; }

    public static bool operator ==(global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? left, global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? right)
    {
        return (right is null) ? (left is null) : right.Equals(left);
    }
    public static bool operator !=(global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? left, global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? right)
    {
        return !(left == right);
    }
    public override bool Equals(object? other)
    {
        if (other is not global::Omnius.Core.RocketPack.Tests.Internal.MessageElement) return false;
        return this.Equals((global::Omnius.Core.RocketPack.Tests.Internal.MessageElement)other);
    }
    public override bool Equals(global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? target)
    {
        if (target is null) return false;
        if (object.ReferenceEquals(this, target)) return true;
        if (this.X0 != target.X0) return false;

        return true;
    }
    public override int GetHashCode() => ___hashCode.Value;

    private sealed class ___CustomSerializer : global::Omnius.Core.RocketPack.IRocketMessageSerializer<global::Omnius.Core.RocketPack.Tests.Internal.MessageElement>
    {
        public void Serialize(ref global::Omnius.Core.RocketPack.RocketMessageWriter w, scoped in global::Omnius.Core.RocketPack.Tests.Internal.MessageElement value, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            if (value.X0 != false)
            {
                w.Put((uint)1);
                w.Put(value.X0);
            }
            w.Put((uint)0);
        }
        public global::Omnius.Core.RocketPack.Tests.Internal.MessageElement Deserialize(ref global::Omnius.Core.RocketPack.RocketMessageReader r, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            bool p_x0 = false;

            for (; ; )
            {
                uint id = r.GetUInt32();
                if (id == 0) break;
                switch (id)
                {
                    case 1:
                        {
                            p_x0 = r.GetBoolean();
                            break;
                        }
                }
            }

            return new global::Omnius.Core.RocketPack.Tests.Internal.MessageElement(p_x0);
        }
    }
}
internal sealed partial class Struct : global::Omnius.Core.RocketPack.RocketMessage<global::Omnius.Core.RocketPack.Tests.Internal.Struct>, global::System.IDisposable
{
    static Struct()
    {
        Formatter = new ___CustomSerializer();
        Empty = new global::Omnius.Core.RocketPack.Tests.Internal.Struct(false, 0, 0, 0, 0, 0, 0, 0, 0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)0, 0.0F, 0.0D, global::Omnius.Core.RocketPack.Utf8String.Empty, global::Omnius.Core.RocketPack.Timestamp64.Zero, global::Omnius.Core.RocketPack.Timestamp96.Zero, global::System.ReadOnlyMemory<byte>.Empty, global::Omnius.Core.Base.MemoryOwner<byte>.Empty, global::System.Array.Empty<global::Omnius.Core.RocketPack.Utf8String>(), new global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>(), global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Empty, global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Empty);
    }

    private readonly global::System.Lazy<int> ___hashCode;

    public static readonly int MaxX19Length = 128;
    public static readonly int MaxX22Length = 256;
    public static readonly int MaxX23Length = 256;
    public static readonly int MaxX24Count = 16;
    public static readonly int MaxX25Count = 32;

    public Struct(bool x0, sbyte x1, short x2, int x3, long x4, byte x5, ushort x6, uint x7, ulong x8, global::Omnius.Core.RocketPack.Tests.Internal.Enum1 x9, global::Omnius.Core.RocketPack.Tests.Internal.Enum2 x10, global::Omnius.Core.RocketPack.Tests.Internal.Enum3 x11, global::Omnius.Core.RocketPack.Tests.Internal.Enum4 x12, global::Omnius.Core.RocketPack.Tests.Internal.Enum5 x13, global::Omnius.Core.RocketPack.Tests.Internal.Enum6 x14, global::Omnius.Core.RocketPack.Tests.Internal.Enum7 x15, global::Omnius.Core.RocketPack.Tests.Internal.Enum8 x16, float x17, double x18, global::Omnius.Core.RocketPack.Utf8String x19, global::Omnius.Core.RocketPack.Timestamp64 x20, global::Omnius.Core.RocketPack.Timestamp96 x21, global::System.ReadOnlyMemory<byte> x22, global::System.Buffers.IMemoryOwner<byte> x23, global::Omnius.Core.RocketPack.Utf8String[] x24, global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String> x25, global::Omnius.Core.RocketPack.Tests.Internal.StructElement x26, global::Omnius.Core.RocketPack.Tests.Internal.MessageElement x27)
    {
        if (x19 is null) throw new global::System.ArgumentNullException("x19");
        if (x19.Length > 128) throw new global::System.ArgumentOutOfRangeException("x19");
        if (x22.Length > 256) throw new global::System.ArgumentOutOfRangeException("x22");
        if (x23 is null) throw new global::System.ArgumentNullException("x23");
        if (x23.Memory.Length > 256) throw new global::System.ArgumentOutOfRangeException("x23");
        if (x24 is null) throw new global::System.ArgumentNullException("x24");
        if (x24.Length > 16) throw new global::System.ArgumentOutOfRangeException("x24");
        foreach (var n in x24)
        {
            if (n is null) throw new global::System.ArgumentNullException("n");
            if (n.Length > 128) throw new global::System.ArgumentOutOfRangeException("n");
        }
        if (x25 is null) throw new global::System.ArgumentNullException("x25");
        if (x25.Count > 32) throw new global::System.ArgumentOutOfRangeException("x25");
        foreach (var n in x25)
        {
            if (n.Value is null) throw new global::System.ArgumentNullException("n.Value");
            if (n.Value.Length > 128) throw new global::System.ArgumentOutOfRangeException("n.Value");
        }
        if (x26 is null) throw new global::System.ArgumentNullException("x26");
        if (x27 is null) throw new global::System.ArgumentNullException("x27");

        this.X0 = x0;
        this.X1 = x1;
        this.X2 = x2;
        this.X3 = x3;
        this.X4 = x4;
        this.X5 = x5;
        this.X6 = x6;
        this.X7 = x7;
        this.X8 = x8;
        this.X9 = x9;
        this.X10 = x10;
        this.X11 = x11;
        this.X12 = x12;
        this.X13 = x13;
        this.X14 = x14;
        this.X15 = x15;
        this.X16 = x16;
        this.X17 = x17;
        this.X18 = x18;
        this.X19 = x19;
        this.X20 = x20;
        this.X21 = x21;
        this.X22 = x22;
        this.X23 = x23;
        this.X24 = global::System.Collections.Immutable.ImmutableList.CreateRange<global::Omnius.Core.RocketPack.Utf8String>(x24);
        this.X25 = global::System.Collections.Immutable.ImmutableDictionary.CreateRange<byte, global::Omnius.Core.RocketPack.Utf8String>(x25);
        this.X26 = x26;
        this.X27 = x27;

        ___hashCode = new global::System.Lazy<int>(() =>
        {
            var ___h = new global::System.HashCode();
            if (x0 != default) ___h.Add(x0.GetHashCode());
            if (x1 != default) ___h.Add(x1.GetHashCode());
            if (x2 != default) ___h.Add(x2.GetHashCode());
            if (x3 != default) ___h.Add(x3.GetHashCode());
            if (x4 != default) ___h.Add(x4.GetHashCode());
            if (x5 != default) ___h.Add(x5.GetHashCode());
            if (x6 != default) ___h.Add(x6.GetHashCode());
            if (x7 != default) ___h.Add(x7.GetHashCode());
            if (x8 != default) ___h.Add(x8.GetHashCode());
            if (x9 != default) ___h.Add(x9.GetHashCode());
            if (x10 != default) ___h.Add(x10.GetHashCode());
            if (x11 != default) ___h.Add(x11.GetHashCode());
            if (x12 != default) ___h.Add(x12.GetHashCode());
            if (x13 != default) ___h.Add(x13.GetHashCode());
            if (x14 != default) ___h.Add(x14.GetHashCode());
            if (x15 != default) ___h.Add(x15.GetHashCode());
            if (x16 != default) ___h.Add(x16.GetHashCode());
            if (x17 != default) ___h.Add(x17.GetHashCode());
            if (x18 != default) ___h.Add(x18.GetHashCode());
            if (!x19.IsEmpty) ___h.Add(x19.GetHashCode());
            if (x20 != default) ___h.Add(x20.GetHashCode());
            if (x21 != default) ___h.Add(x21.GetHashCode());
            if (!x22.IsEmpty) ___h.Add(global::Omnius.Core.Base.Helpers.ObjectHelper.GetHashCode(x22.Span));
            if (!x23.Memory.IsEmpty) ___h.Add(global::Omnius.Core.Base.Helpers.ObjectHelper.GetHashCode(x23.Memory.Span));
            foreach (var n in x24)
            {
                if (!n.IsEmpty) ___h.Add(n.GetHashCode());
            }
            foreach (var n in x25)
            {
                if (n.Key != default) ___h.Add(n.Key.GetHashCode());
                if (!n.Value.IsEmpty) ___h.Add(n.Value.GetHashCode());
            }
            if (x26 != default) ___h.Add(x26.GetHashCode());
            if (x27 != default) ___h.Add(x27.GetHashCode());
            return ___h.ToHashCode();
        });
    }

    public void Dispose()
    {
        this.X23.Dispose();
    }

    public bool X0 { get; }
    public sbyte X1 { get; }
    public short X2 { get; }
    public int X3 { get; }
    public long X4 { get; }
    public byte X5 { get; }
    public ushort X6 { get; }
    public uint X7 { get; }
    public ulong X8 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum1 X9 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum2 X10 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum3 X11 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum4 X12 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum5 X13 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum6 X14 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum7 X15 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum8 X16 { get; }
    public float X17 { get; }
    public double X18 { get; }
    public global::Omnius.Core.RocketPack.Utf8String X19 { get; }
    public global::Omnius.Core.RocketPack.Timestamp64 X20 { get; }
    public global::Omnius.Core.RocketPack.Timestamp96 X21 { get; }
    public global::System.ReadOnlyMemory<byte> X22 { get; }
    public global::System.Buffers.IMemoryOwner<byte> X23 { get; }
    public global::System.Collections.Immutable.ImmutableList<global::Omnius.Core.RocketPack.Utf8String> X24 { get; }
    public global::System.Collections.Immutable.ImmutableDictionary<byte, global::Omnius.Core.RocketPack.Utf8String> X25 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.StructElement X26 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.MessageElement X27 { get; }

    public static bool operator ==(global::Omnius.Core.RocketPack.Tests.Internal.Struct? left, global::Omnius.Core.RocketPack.Tests.Internal.Struct? right)
    {
        return (right is null) ? (left is null) : right.Equals(left);
    }
    public static bool operator !=(global::Omnius.Core.RocketPack.Tests.Internal.Struct? left, global::Omnius.Core.RocketPack.Tests.Internal.Struct? right)
    {
        return !(left == right);
    }
    public override bool Equals(object? other)
    {
        if (other is not global::Omnius.Core.RocketPack.Tests.Internal.Struct) return false;
        return this.Equals((global::Omnius.Core.RocketPack.Tests.Internal.Struct)other);
    }
    public override bool Equals(global::Omnius.Core.RocketPack.Tests.Internal.Struct? target)
    {
        if (target is null) return false;
        if (object.ReferenceEquals(this, target)) return true;
        if (this.X0 != target.X0) return false;
        if (this.X1 != target.X1) return false;
        if (this.X2 != target.X2) return false;
        if (this.X3 != target.X3) return false;
        if (this.X4 != target.X4) return false;
        if (this.X5 != target.X5) return false;
        if (this.X6 != target.X6) return false;
        if (this.X7 != target.X7) return false;
        if (this.X8 != target.X8) return false;
        if (this.X9 != target.X9) return false;
        if (this.X10 != target.X10) return false;
        if (this.X11 != target.X11) return false;
        if (this.X12 != target.X12) return false;
        if (this.X13 != target.X13) return false;
        if (this.X14 != target.X14) return false;
        if (this.X15 != target.X15) return false;
        if (this.X16 != target.X16) return false;
        if (this.X17 != target.X17) return false;
        if (this.X18 != target.X18) return false;
        if (this.X19 != target.X19) return false;
        if (this.X20 != target.X20) return false;
        if (this.X21 != target.X21) return false;
        if (!global::Omnius.Core.Base.BytesOperations.Equals(this.X22.Span, target.X22.Span)) return false;
        if (!global::Omnius.Core.Base.BytesOperations.Equals(this.X23.Memory.Span, target.X23.Memory.Span)) return false;
        if (!global::Omnius.Core.Base.Helpers.CollectionHelper.Equals(this.X24, target.X24)) return false;
        if (!global::Omnius.Core.Base.Helpers.CollectionHelper.Equals(this.X25, target.X25)) return false;
        if (this.X26 != target.X26) return false;
        if (this.X27 != target.X27) return false;

        return true;
    }
    public override int GetHashCode() => ___hashCode.Value;

    private sealed class ___CustomSerializer : global::Omnius.Core.RocketPack.IRocketMessageSerializer<global::Omnius.Core.RocketPack.Tests.Internal.Struct>
    {
        public void Serialize(ref global::Omnius.Core.RocketPack.RocketMessageWriter w, scoped in global::Omnius.Core.RocketPack.Tests.Internal.Struct value, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            w.Put(value.X0);
            w.Put(value.X1);
            w.Put(value.X2);
            w.Put(value.X3);
            w.Put(value.X4);
            w.Put(value.X5);
            w.Put(value.X6);
            w.Put(value.X7);
            w.Put(value.X8);
            w.Put((long)value.X9);
            w.Put((long)value.X10);
            w.Put((long)value.X11);
            w.Put((long)value.X12);
            w.Put((ulong)value.X13);
            w.Put((ulong)value.X14);
            w.Put((ulong)value.X15);
            w.Put((ulong)value.X16);
            w.Put(value.X17);
            w.Put(value.X18);
            w.Put(value.X19);
            w.Put(value.X20);
            w.Put(value.X21);
            w.Put(value.X22.Span);
            w.Put(value.X23.Memory.Span);
            w.Put((uint)value.X24.Count);
            foreach (var n in value.X24)
            {
                w.Put(n);
            }
            w.Put((uint)value.X25.Count);
            foreach (var n in value.X25)
            {
                w.Put(n.Key);
                w.Put(n.Value);
            }
            global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Formatter.Serialize(ref w, value.X26, depth + 1);
            global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Formatter.Serialize(ref w, value.X27, depth + 1);
        }
        public global::Omnius.Core.RocketPack.Tests.Internal.Struct Deserialize(ref global::Omnius.Core.RocketPack.RocketMessageReader r, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            bool p_x0 = false;
            sbyte p_x1 = 0;
            short p_x2 = 0;
            int p_x3 = 0;
            long p_x4 = 0;
            byte p_x5 = 0;
            ushort p_x6 = 0;
            uint p_x7 = 0;
            ulong p_x8 = 0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum1 p_x9 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum2 p_x10 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum3 p_x11 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum4 p_x12 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum5 p_x13 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum6 p_x14 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum7 p_x15 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum8 p_x16 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)0;
            float p_x17 = 0.0F;
            double p_x18 = 0.0D;
            global::Omnius.Core.RocketPack.Utf8String p_x19 = global::Omnius.Core.RocketPack.Utf8String.Empty;
            global::Omnius.Core.RocketPack.Timestamp64 p_x20 = global::Omnius.Core.RocketPack.Timestamp64.Zero;
            global::Omnius.Core.RocketPack.Timestamp96 p_x21 = global::Omnius.Core.RocketPack.Timestamp96.Zero;
            global::System.ReadOnlyMemory<byte> p_x22 = global::System.ReadOnlyMemory<byte>.Empty;
            global::System.Buffers.IMemoryOwner<byte> p_x23 = global::Omnius.Core.Base.MemoryOwner<byte>.Empty;
            global::Omnius.Core.RocketPack.Utf8String[] p_x24 = global::System.Array.Empty<global::Omnius.Core.RocketPack.Utf8String>();
            global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String> p_x25 = new global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>();
            global::Omnius.Core.RocketPack.Tests.Internal.StructElement p_x26 = global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Empty;
            global::Omnius.Core.RocketPack.Tests.Internal.MessageElement p_x27 = global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Empty;

            {
                p_x0 = r.GetBoolean();
            }
            {
                p_x1 = r.GetInt8();
            }
            {
                p_x2 = r.GetInt16();
            }
            {
                p_x3 = r.GetInt32();
            }
            {
                p_x4 = r.GetInt64();
            }
            {
                p_x5 = r.GetUInt8();
            }
            {
                p_x6 = r.GetUInt16();
            }
            {
                p_x7 = r.GetUInt32();
            }
            {
                p_x8 = r.GetUInt64();
            }
            {
                p_x9 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)r.GetInt64();
            }
            {
                p_x10 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)r.GetInt64();
            }
            {
                p_x11 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)r.GetInt64();
            }
            {
                p_x12 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)r.GetInt64();
            }
            {
                p_x13 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)r.GetUInt64();
            }
            {
                p_x14 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)r.GetUInt64();
            }
            {
                p_x15 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)r.GetUInt64();
            }
            {
                p_x16 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)r.GetUInt64();
            }
            {
                p_x17 = r.GetFloat32();
            }
            {
                p_x18 = r.GetFloat64();
            }
            {
                p_x19 = r.GetString(128);
            }
            {
                p_x20 = r.GetTimestamp64();
            }
            {
                p_x21 = r.GetTimestamp96();
            }
            {
                p_x22 = r.GetMemory(256);
            }
            {
                p_x23 = r.GetRecyclableMemory(256);
            }
            {
                var length = r.GetUInt32();
                p_x24 = new global::Omnius.Core.RocketPack.Utf8String[length];
                for (int i = 0; i < p_x24.Length; i++)
                {
                    p_x24[i] = r.GetString(128);
                }
            }
            {
                var length = r.GetUInt32();
                p_x25 = new global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>();
                byte t_key = 0;
                global::Omnius.Core.RocketPack.Utf8String t_value = global::Omnius.Core.RocketPack.Utf8String.Empty;
                for (int i = 0; i < length; i++)
                {
                    t_key = r.GetUInt8();
                    t_value = r.GetString(128);
                    p_x25[t_key] = t_value;
                }
            }
            {
                p_x26 = global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Formatter.Deserialize(ref r, depth + 1);
            }
            {
                p_x27 = global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Formatter.Deserialize(ref r, depth + 1);
            }
            return new global::Omnius.Core.RocketPack.Tests.Internal.Struct(p_x0, p_x1, p_x2, p_x3, p_x4, p_x5, p_x6, p_x7, p_x8, p_x9, p_x10, p_x11, p_x12, p_x13, p_x14, p_x15, p_x16, p_x17, p_x18, p_x19, p_x20, p_x21, p_x22, p_x23, p_x24, p_x25, p_x26, p_x27);
        }
    }
}
internal sealed partial class Message : global::Omnius.Core.RocketPack.RocketMessage<global::Omnius.Core.RocketPack.Tests.Internal.Message>, global::System.IDisposable
{
    static Message()
    {
        Formatter = new ___CustomSerializer();
        Empty = new global::Omnius.Core.RocketPack.Tests.Internal.Message(false, 0, 0, 0, 0, 0, 0, 0, 0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)0, (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)0, 0.0F, 0.0D, global::Omnius.Core.RocketPack.Utf8String.Empty, global::Omnius.Core.RocketPack.Timestamp64.Zero, global::Omnius.Core.RocketPack.Timestamp96.Zero, global::System.ReadOnlyMemory<byte>.Empty, global::Omnius.Core.Base.MemoryOwner<byte>.Empty, global::System.Array.Empty<global::Omnius.Core.RocketPack.Utf8String>(), new global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>(), global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Empty, global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Empty);
    }

    private readonly global::System.Lazy<int> ___hashCode;

    public static readonly int MaxX19Length = 128;
    public static readonly int MaxX22Length = 256;
    public static readonly int MaxX23Length = 256;
    public static readonly int MaxX24Count = 16;
    public static readonly int MaxX25Count = 32;

    public Message(bool x0, sbyte x1, short x2, int x3, long x4, byte x5, ushort x6, uint x7, ulong x8, global::Omnius.Core.RocketPack.Tests.Internal.Enum1 x9, global::Omnius.Core.RocketPack.Tests.Internal.Enum2 x10, global::Omnius.Core.RocketPack.Tests.Internal.Enum3 x11, global::Omnius.Core.RocketPack.Tests.Internal.Enum4 x12, global::Omnius.Core.RocketPack.Tests.Internal.Enum5 x13, global::Omnius.Core.RocketPack.Tests.Internal.Enum6 x14, global::Omnius.Core.RocketPack.Tests.Internal.Enum7 x15, global::Omnius.Core.RocketPack.Tests.Internal.Enum8 x16, float x17, double x18, global::Omnius.Core.RocketPack.Utf8String x19, global::Omnius.Core.RocketPack.Timestamp64 x20, global::Omnius.Core.RocketPack.Timestamp96 x21, global::System.ReadOnlyMemory<byte> x22, global::System.Buffers.IMemoryOwner<byte> x23, global::Omnius.Core.RocketPack.Utf8String[] x24, global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String> x25, global::Omnius.Core.RocketPack.Tests.Internal.StructElement x26, global::Omnius.Core.RocketPack.Tests.Internal.MessageElement x27)
    {
        if (x19 is null) throw new global::System.ArgumentNullException("x19");
        if (x19.Length > 128) throw new global::System.ArgumentOutOfRangeException("x19");
        if (x22.Length > 256) throw new global::System.ArgumentOutOfRangeException("x22");
        if (x23 is null) throw new global::System.ArgumentNullException("x23");
        if (x23.Memory.Length > 256) throw new global::System.ArgumentOutOfRangeException("x23");
        if (x24 is null) throw new global::System.ArgumentNullException("x24");
        if (x24.Length > 16) throw new global::System.ArgumentOutOfRangeException("x24");
        foreach (var n in x24)
        {
            if (n is null) throw new global::System.ArgumentNullException("n");
            if (n.Length > 128) throw new global::System.ArgumentOutOfRangeException("n");
        }
        if (x25 is null) throw new global::System.ArgumentNullException("x25");
        if (x25.Count > 32) throw new global::System.ArgumentOutOfRangeException("x25");
        foreach (var n in x25)
        {
            if (n.Value is null) throw new global::System.ArgumentNullException("n.Value");
            if (n.Value.Length > 128) throw new global::System.ArgumentOutOfRangeException("n.Value");
        }
        if (x26 is null) throw new global::System.ArgumentNullException("x26");
        if (x27 is null) throw new global::System.ArgumentNullException("x27");

        this.X0 = x0;
        this.X1 = x1;
        this.X2 = x2;
        this.X3 = x3;
        this.X4 = x4;
        this.X5 = x5;
        this.X6 = x6;
        this.X7 = x7;
        this.X8 = x8;
        this.X9 = x9;
        this.X10 = x10;
        this.X11 = x11;
        this.X12 = x12;
        this.X13 = x13;
        this.X14 = x14;
        this.X15 = x15;
        this.X16 = x16;
        this.X17 = x17;
        this.X18 = x18;
        this.X19 = x19;
        this.X20 = x20;
        this.X21 = x21;
        this.X22 = x22;
        this.X23 = x23;
        this.X24 = global::System.Collections.Immutable.ImmutableList.CreateRange<global::Omnius.Core.RocketPack.Utf8String>(x24);
        this.X25 = global::System.Collections.Immutable.ImmutableDictionary.CreateRange<byte, global::Omnius.Core.RocketPack.Utf8String>(x25);
        this.X26 = x26;
        this.X27 = x27;

        ___hashCode = new global::System.Lazy<int>(() =>
        {
            var ___h = new global::System.HashCode();
            if (x0 != default) ___h.Add(x0.GetHashCode());
            if (x1 != default) ___h.Add(x1.GetHashCode());
            if (x2 != default) ___h.Add(x2.GetHashCode());
            if (x3 != default) ___h.Add(x3.GetHashCode());
            if (x4 != default) ___h.Add(x4.GetHashCode());
            if (x5 != default) ___h.Add(x5.GetHashCode());
            if (x6 != default) ___h.Add(x6.GetHashCode());
            if (x7 != default) ___h.Add(x7.GetHashCode());
            if (x8 != default) ___h.Add(x8.GetHashCode());
            if (x9 != default) ___h.Add(x9.GetHashCode());
            if (x10 != default) ___h.Add(x10.GetHashCode());
            if (x11 != default) ___h.Add(x11.GetHashCode());
            if (x12 != default) ___h.Add(x12.GetHashCode());
            if (x13 != default) ___h.Add(x13.GetHashCode());
            if (x14 != default) ___h.Add(x14.GetHashCode());
            if (x15 != default) ___h.Add(x15.GetHashCode());
            if (x16 != default) ___h.Add(x16.GetHashCode());
            if (x17 != default) ___h.Add(x17.GetHashCode());
            if (x18 != default) ___h.Add(x18.GetHashCode());
            if (!x19.IsEmpty) ___h.Add(x19.GetHashCode());
            if (x20 != default) ___h.Add(x20.GetHashCode());
            if (x21 != default) ___h.Add(x21.GetHashCode());
            if (!x22.IsEmpty) ___h.Add(global::Omnius.Core.Base.Helpers.ObjectHelper.GetHashCode(x22.Span));
            if (!x23.Memory.IsEmpty) ___h.Add(global::Omnius.Core.Base.Helpers.ObjectHelper.GetHashCode(x23.Memory.Span));
            foreach (var n in x24)
            {
                if (!n.IsEmpty) ___h.Add(n.GetHashCode());
            }
            foreach (var n in x25)
            {
                if (n.Key != default) ___h.Add(n.Key.GetHashCode());
                if (!n.Value.IsEmpty) ___h.Add(n.Value.GetHashCode());
            }
            if (x26 != default) ___h.Add(x26.GetHashCode());
            if (x27 != default) ___h.Add(x27.GetHashCode());
            return ___h.ToHashCode();
        });
    }

    public void Dispose()
    {
        this.X23.Dispose();
    }

    public bool X0 { get; }
    public sbyte X1 { get; }
    public short X2 { get; }
    public int X3 { get; }
    public long X4 { get; }
    public byte X5 { get; }
    public ushort X6 { get; }
    public uint X7 { get; }
    public ulong X8 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum1 X9 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum2 X10 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum3 X11 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum4 X12 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum5 X13 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum6 X14 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum7 X15 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum8 X16 { get; }
    public float X17 { get; }
    public double X18 { get; }
    public global::Omnius.Core.RocketPack.Utf8String X19 { get; }
    public global::Omnius.Core.RocketPack.Timestamp64 X20 { get; }
    public global::Omnius.Core.RocketPack.Timestamp96 X21 { get; }
    public global::System.ReadOnlyMemory<byte> X22 { get; }
    public global::System.Buffers.IMemoryOwner<byte> X23 { get; }
    public global::System.Collections.Immutable.ImmutableList<global::Omnius.Core.RocketPack.Utf8String> X24 { get; }
    public global::System.Collections.Immutable.ImmutableDictionary<byte, global::Omnius.Core.RocketPack.Utf8String> X25 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.StructElement X26 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.MessageElement X27 { get; }

    public static bool operator ==(global::Omnius.Core.RocketPack.Tests.Internal.Message? left, global::Omnius.Core.RocketPack.Tests.Internal.Message? right)
    {
        return (right is null) ? (left is null) : right.Equals(left);
    }
    public static bool operator !=(global::Omnius.Core.RocketPack.Tests.Internal.Message? left, global::Omnius.Core.RocketPack.Tests.Internal.Message? right)
    {
        return !(left == right);
    }
    public override bool Equals(object? other)
    {
        if (other is not global::Omnius.Core.RocketPack.Tests.Internal.Message) return false;
        return this.Equals((global::Omnius.Core.RocketPack.Tests.Internal.Message)other);
    }
    public override bool Equals(global::Omnius.Core.RocketPack.Tests.Internal.Message? target)
    {
        if (target is null) return false;
        if (object.ReferenceEquals(this, target)) return true;
        if (this.X0 != target.X0) return false;
        if (this.X1 != target.X1) return false;
        if (this.X2 != target.X2) return false;
        if (this.X3 != target.X3) return false;
        if (this.X4 != target.X4) return false;
        if (this.X5 != target.X5) return false;
        if (this.X6 != target.X6) return false;
        if (this.X7 != target.X7) return false;
        if (this.X8 != target.X8) return false;
        if (this.X9 != target.X9) return false;
        if (this.X10 != target.X10) return false;
        if (this.X11 != target.X11) return false;
        if (this.X12 != target.X12) return false;
        if (this.X13 != target.X13) return false;
        if (this.X14 != target.X14) return false;
        if (this.X15 != target.X15) return false;
        if (this.X16 != target.X16) return false;
        if (this.X17 != target.X17) return false;
        if (this.X18 != target.X18) return false;
        if (this.X19 != target.X19) return false;
        if (this.X20 != target.X20) return false;
        if (this.X21 != target.X21) return false;
        if (!global::Omnius.Core.Base.BytesOperations.Equals(this.X22.Span, target.X22.Span)) return false;
        if (!global::Omnius.Core.Base.BytesOperations.Equals(this.X23.Memory.Span, target.X23.Memory.Span)) return false;
        if (!global::Omnius.Core.Base.Helpers.CollectionHelper.Equals(this.X24, target.X24)) return false;
        if (!global::Omnius.Core.Base.Helpers.CollectionHelper.Equals(this.X25, target.X25)) return false;
        if (this.X26 != target.X26) return false;
        if (this.X27 != target.X27) return false;

        return true;
    }
    public override int GetHashCode() => ___hashCode.Value;

    private sealed class ___CustomSerializer : global::Omnius.Core.RocketPack.IRocketMessageSerializer<global::Omnius.Core.RocketPack.Tests.Internal.Message>
    {
        public void Serialize(ref global::Omnius.Core.RocketPack.RocketMessageWriter w, scoped in global::Omnius.Core.RocketPack.Tests.Internal.Message value, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            if (value.X0 != false)
            {
                w.Put((uint)1);
                w.Put(value.X0);
            }
            if (value.X1 != 0)
            {
                w.Put((uint)2);
                w.Put(value.X1);
            }
            if (value.X2 != 0)
            {
                w.Put((uint)3);
                w.Put(value.X2);
            }
            if (value.X3 != 0)
            {
                w.Put((uint)4);
                w.Put(value.X3);
            }
            if (value.X4 != 0)
            {
                w.Put((uint)5);
                w.Put(value.X4);
            }
            if (value.X5 != 0)
            {
                w.Put((uint)6);
                w.Put(value.X5);
            }
            if (value.X6 != 0)
            {
                w.Put((uint)7);
                w.Put(value.X6);
            }
            if (value.X7 != 0)
            {
                w.Put((uint)8);
                w.Put(value.X7);
            }
            if (value.X8 != 0)
            {
                w.Put((uint)9);
                w.Put(value.X8);
            }
            if (value.X9 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)0)
            {
                w.Put((uint)10);
                w.Put((long)value.X9);
            }
            if (value.X10 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)0)
            {
                w.Put((uint)11);
                w.Put((long)value.X10);
            }
            if (value.X11 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)0)
            {
                w.Put((uint)12);
                w.Put((long)value.X11);
            }
            if (value.X12 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)0)
            {
                w.Put((uint)13);
                w.Put((long)value.X12);
            }
            if (value.X13 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)0)
            {
                w.Put((uint)14);
                w.Put((ulong)value.X13);
            }
            if (value.X14 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)0)
            {
                w.Put((uint)15);
                w.Put((ulong)value.X14);
            }
            if (value.X15 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)0)
            {
                w.Put((uint)16);
                w.Put((ulong)value.X15);
            }
            if (value.X16 != (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)0)
            {
                w.Put((uint)17);
                w.Put((ulong)value.X16);
            }
            if (value.X17 != 0.0F)
            {
                w.Put((uint)18);
                w.Put(value.X17);
            }
            if (value.X18 != 0.0D)
            {
                w.Put((uint)19);
                w.Put(value.X18);
            }
            if (value.X19 != global::Omnius.Core.RocketPack.Utf8String.Empty)
            {
                w.Put((uint)20);
                w.Put(value.X19);
            }
            if (value.X20 != global::Omnius.Core.RocketPack.Timestamp64.Zero)
            {
                w.Put((uint)21);
                w.Put(value.X20);
            }
            if (value.X21 != global::Omnius.Core.RocketPack.Timestamp96.Zero)
            {
                w.Put((uint)22);
                w.Put(value.X21);
            }
            if (!value.X22.IsEmpty)
            {
                w.Put((uint)23);
                w.Put(value.X22.Span);
            }
            if (!value.X23.Memory.IsEmpty)
            {
                w.Put((uint)24);
                w.Put(value.X23.Memory.Span);
            }
            if (value.X24.Count != 0)
            {
                w.Put((uint)25);
                w.Put((uint)value.X24.Count);
                foreach (var n in value.X24)
                {
                    w.Put(n);
                }
            }
            if (value.X25.Count != 0)
            {
                w.Put((uint)26);
                w.Put((uint)value.X25.Count);
                foreach (var n in value.X25)
                {
                    w.Put(n.Key);
                    w.Put(n.Value);
                }
            }
            if (value.X26 != global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Empty)
            {
                w.Put((uint)27);
                global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Formatter.Serialize(ref w, value.X26, depth + 1);
            }
            if (value.X27 != global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Empty)
            {
                w.Put((uint)28);
                global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Formatter.Serialize(ref w, value.X27, depth + 1);
            }
            w.Put((uint)0);
        }
        public global::Omnius.Core.RocketPack.Tests.Internal.Message Deserialize(ref global::Omnius.Core.RocketPack.RocketMessageReader r, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            bool p_x0 = false;
            sbyte p_x1 = 0;
            short p_x2 = 0;
            int p_x3 = 0;
            long p_x4 = 0;
            byte p_x5 = 0;
            ushort p_x6 = 0;
            uint p_x7 = 0;
            ulong p_x8 = 0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum1 p_x9 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum2 p_x10 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum3 p_x11 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum4 p_x12 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum5 p_x13 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum6 p_x14 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum7 p_x15 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)0;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum8 p_x16 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)0;
            float p_x17 = 0.0F;
            double p_x18 = 0.0D;
            global::Omnius.Core.RocketPack.Utf8String p_x19 = global::Omnius.Core.RocketPack.Utf8String.Empty;
            global::Omnius.Core.RocketPack.Timestamp64 p_x20 = global::Omnius.Core.RocketPack.Timestamp64.Zero;
            global::Omnius.Core.RocketPack.Timestamp96 p_x21 = global::Omnius.Core.RocketPack.Timestamp96.Zero;
            global::System.ReadOnlyMemory<byte> p_x22 = global::System.ReadOnlyMemory<byte>.Empty;
            global::System.Buffers.IMemoryOwner<byte> p_x23 = global::Omnius.Core.Base.MemoryOwner<byte>.Empty;
            global::Omnius.Core.RocketPack.Utf8String[] p_x24 = global::System.Array.Empty<global::Omnius.Core.RocketPack.Utf8String>();
            global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String> p_x25 = new global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>();
            global::Omnius.Core.RocketPack.Tests.Internal.StructElement p_x26 = global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Empty;
            global::Omnius.Core.RocketPack.Tests.Internal.MessageElement p_x27 = global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Empty;

            for (; ; )
            {
                uint id = r.GetUInt32();
                if (id == 0) break;
                switch (id)
                {
                    case 1:
                        {
                            p_x0 = r.GetBoolean();
                            break;
                        }
                    case 2:
                        {
                            p_x1 = r.GetInt8();
                            break;
                        }
                    case 3:
                        {
                            p_x2 = r.GetInt16();
                            break;
                        }
                    case 4:
                        {
                            p_x3 = r.GetInt32();
                            break;
                        }
                    case 5:
                        {
                            p_x4 = r.GetInt64();
                            break;
                        }
                    case 6:
                        {
                            p_x5 = r.GetUInt8();
                            break;
                        }
                    case 7:
                        {
                            p_x6 = r.GetUInt16();
                            break;
                        }
                    case 8:
                        {
                            p_x7 = r.GetUInt32();
                            break;
                        }
                    case 9:
                        {
                            p_x8 = r.GetUInt64();
                            break;
                        }
                    case 10:
                        {
                            p_x9 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)r.GetInt64();
                            break;
                        }
                    case 11:
                        {
                            p_x10 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)r.GetInt64();
                            break;
                        }
                    case 12:
                        {
                            p_x11 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)r.GetInt64();
                            break;
                        }
                    case 13:
                        {
                            p_x12 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)r.GetInt64();
                            break;
                        }
                    case 14:
                        {
                            p_x13 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)r.GetUInt64();
                            break;
                        }
                    case 15:
                        {
                            p_x14 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)r.GetUInt64();
                            break;
                        }
                    case 16:
                        {
                            p_x15 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)r.GetUInt64();
                            break;
                        }
                    case 17:
                        {
                            p_x16 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)r.GetUInt64();
                            break;
                        }
                    case 18:
                        {
                            p_x17 = r.GetFloat32();
                            break;
                        }
                    case 19:
                        {
                            p_x18 = r.GetFloat64();
                            break;
                        }
                    case 20:
                        {
                            p_x19 = r.GetString(128);
                            break;
                        }
                    case 21:
                        {
                            p_x20 = r.GetTimestamp64();
                            break;
                        }
                    case 22:
                        {
                            p_x21 = r.GetTimestamp96();
                            break;
                        }
                    case 23:
                        {
                            p_x22 = r.GetMemory(256);
                            break;
                        }
                    case 24:
                        {
                            p_x23 = r.GetRecyclableMemory(256);
                            break;
                        }
                    case 25:
                        {
                            var length = r.GetUInt32();
                            p_x24 = new global::Omnius.Core.RocketPack.Utf8String[length];
                            for (int i = 0; i < p_x24.Length; i++)
                            {
                                p_x24[i] = r.GetString(128);
                            }
                            break;
                        }
                    case 26:
                        {
                            var length = r.GetUInt32();
                            p_x25 = new global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>();
                            byte t_key = 0;
                            global::Omnius.Core.RocketPack.Utf8String t_value = global::Omnius.Core.RocketPack.Utf8String.Empty;
                            for (int i = 0; i < length; i++)
                            {
                                t_key = r.GetUInt8();
                                t_value = r.GetString(128);
                                p_x25[t_key] = t_value;
                            }
                            break;
                        }
                    case 27:
                        {
                            p_x26 = global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Formatter.Deserialize(ref r, depth + 1);
                            break;
                        }
                    case 28:
                        {
                            p_x27 = global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Formatter.Deserialize(ref r, depth + 1);
                            break;
                        }
                }
            }

            return new global::Omnius.Core.RocketPack.Tests.Internal.Message(p_x0, p_x1, p_x2, p_x3, p_x4, p_x5, p_x6, p_x7, p_x8, p_x9, p_x10, p_x11, p_x12, p_x13, p_x14, p_x15, p_x16, p_x17, p_x18, p_x19, p_x20, p_x21, p_x22, p_x23, p_x24, p_x25, p_x26, p_x27);
        }
    }
}
internal sealed partial class NullableMessage : global::Omnius.Core.RocketPack.RocketMessage<global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage>, global::System.IDisposable
{
    static NullableMessage()
    {
        Formatter = new ___CustomSerializer();
        Empty = new global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage(null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null);
    }

    private readonly global::System.Lazy<int> ___hashCode;

    public static readonly int MaxX19Length = 128;
    public static readonly int MaxX22Length = 256;
    public static readonly int MaxX23Length = 256;
    public static readonly int MaxX24Count = 16;
    public static readonly int MaxX25Count = 32;

    public NullableMessage(bool? x0, sbyte? x1, short? x2, int? x3, long? x4, byte? x5, ushort? x6, uint? x7, ulong? x8, global::Omnius.Core.RocketPack.Tests.Internal.Enum1? x9, global::Omnius.Core.RocketPack.Tests.Internal.Enum2? x10, global::Omnius.Core.RocketPack.Tests.Internal.Enum3? x11, global::Omnius.Core.RocketPack.Tests.Internal.Enum4? x12, global::Omnius.Core.RocketPack.Tests.Internal.Enum5? x13, global::Omnius.Core.RocketPack.Tests.Internal.Enum6? x14, global::Omnius.Core.RocketPack.Tests.Internal.Enum7? x15, global::Omnius.Core.RocketPack.Tests.Internal.Enum8? x16, float? x17, double? x18, global::Omnius.Core.RocketPack.Utf8String? x19, global::Omnius.Core.RocketPack.Timestamp64? x20, global::Omnius.Core.RocketPack.Timestamp96? x21, global::System.ReadOnlyMemory<byte>? x22, global::System.Buffers.IMemoryOwner<byte>? x23, global::Omnius.Core.RocketPack.Utf8String[]? x24, global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>? x25, global::Omnius.Core.RocketPack.Tests.Internal.StructElement? x26, global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? x27)
    {
        if (x19 is not null && x19.Length > 128) throw new global::System.ArgumentOutOfRangeException("x19");
        if (x22 is not null && x22.Value.Length > 256) throw new global::System.ArgumentOutOfRangeException("x22");
        if (x23 is not null && x23.Memory.Length > 256) throw new global::System.ArgumentOutOfRangeException("x23");
        if (x24 is not null && x24.Length > 16) throw new global::System.ArgumentOutOfRangeException("x24");
        if (x24 is not null)
        {
            foreach (var n in x24)
            {
                if (n is null) throw new global::System.ArgumentNullException("n");
                if (n.Length > 128) throw new global::System.ArgumentOutOfRangeException("n");
            }
        }
        if (x25 is not null && x25.Count > 32) throw new global::System.ArgumentOutOfRangeException("x25");
        if (x25 is not null)
        {
            foreach (var n in x25)
            {
                if (n.Value is null) throw new global::System.ArgumentNullException("n.Value");
                if (n.Value.Length > 128) throw new global::System.ArgumentOutOfRangeException("n.Value");
            }
        }
        this.X0 = x0;
        this.X1 = x1;
        this.X2 = x2;
        this.X3 = x3;
        this.X4 = x4;
        this.X5 = x5;
        this.X6 = x6;
        this.X7 = x7;
        this.X8 = x8;
        this.X9 = x9;
        this.X10 = x10;
        this.X11 = x11;
        this.X12 = x12;
        this.X13 = x13;
        this.X14 = x14;
        this.X15 = x15;
        this.X16 = x16;
        this.X17 = x17;
        this.X18 = x18;
        this.X19 = x19;
        this.X20 = x20;
        this.X21 = x21;
        this.X22 = x22;
        this.X23 = x23;
        if (x24 != null)
        {
            this.X24 = global::System.Collections.Immutable.ImmutableList.CreateRange<global::Omnius.Core.RocketPack.Utf8String>(x24);
        }
        else
        {
            this.X24 = null;
        }
        if(x25 != null)
        {
            this.X25 = global::System.Collections.Immutable.ImmutableDictionary.CreateRange<byte, global::Omnius.Core.RocketPack.Utf8String>(x25);
        }
        else
        {
            this.X25 = null;
        }
        this.X26 = x26;
        this.X27 = x27;

        ___hashCode = new global::System.Lazy<int>(() =>
        {
            var ___h = new global::System.HashCode();
            if (x0 != default) ___h.Add(x0.GetHashCode());
            if (x1 != default) ___h.Add(x1.GetHashCode());
            if (x2 != default) ___h.Add(x2.GetHashCode());
            if (x3 != default) ___h.Add(x3.GetHashCode());
            if (x4 != default) ___h.Add(x4.GetHashCode());
            if (x5 != default) ___h.Add(x5.GetHashCode());
            if (x6 != default) ___h.Add(x6.GetHashCode());
            if (x7 != default) ___h.Add(x7.GetHashCode());
            if (x8 != default) ___h.Add(x8.GetHashCode());
            if (x9 != default) ___h.Add(x9.GetHashCode());
            if (x10 != default) ___h.Add(x10.GetHashCode());
            if (x11 != default) ___h.Add(x11.GetHashCode());
            if (x12 != default) ___h.Add(x12.GetHashCode());
            if (x13 != default) ___h.Add(x13.GetHashCode());
            if (x14 != default) ___h.Add(x14.GetHashCode());
            if (x15 != default) ___h.Add(x15.GetHashCode());
            if (x16 != default) ___h.Add(x16.GetHashCode());
            if (x17 != default) ___h.Add(x17.GetHashCode());
            if (x18 != default) ___h.Add(x18.GetHashCode());
            if (x19 is not null && !x19.IsEmpty) ___h.Add(x19.GetHashCode());
            if (x20 != default) ___h.Add(x20.GetHashCode());
            if (x21 != default) ___h.Add(x21.GetHashCode());
            if (x22 is not null && !x22.Value.IsEmpty) ___h.Add(global::Omnius.Core.Base.Helpers.ObjectHelper.GetHashCode(x22.Value.Span));
            if (x23 is not null && !x23.Memory.IsEmpty) ___h.Add(global::Omnius.Core.Base.Helpers.ObjectHelper.GetHashCode(x23.Memory.Span));
            if(x24 != null)
            {
                foreach (var n in x24)
                {
                    if (!n.IsEmpty) ___h.Add(n.GetHashCode());
                }
            }
            if(x25 != null)
            {
                foreach (var n in x25)
                {
                    if (n.Key != default) ___h.Add(n.Key.GetHashCode());
                    if (!n.Value.IsEmpty) ___h.Add(n.Value.GetHashCode());
                }
            }
            if (x26 != default) ___h.Add(x26.GetHashCode());
            if (x27 != default) ___h.Add(x27.GetHashCode());
            return ___h.ToHashCode();
        });
    }

    public void Dispose()
    {
        if (this.X23 is not null) this.X23.Dispose();
    }

    public bool? X0 { get; }
    public sbyte? X1 { get; }
    public short? X2 { get; }
    public int? X3 { get; }
    public long? X4 { get; }
    public byte? X5 { get; }
    public ushort? X6 { get; }
    public uint? X7 { get; }
    public ulong? X8 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum1? X9 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum2? X10 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum3? X11 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum4? X12 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum5? X13 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum6? X14 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum7? X15 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.Enum8? X16 { get; }
    public float? X17 { get; }
    public double? X18 { get; }
    public global::Omnius.Core.RocketPack.Utf8String? X19 { get; }
    public global::Omnius.Core.RocketPack.Timestamp64? X20 { get; }
    public global::Omnius.Core.RocketPack.Timestamp96? X21 { get; }
    public global::System.ReadOnlyMemory<byte>? X22 { get; }
    public global::System.Buffers.IMemoryOwner<byte>? X23 { get; }
    public global::System.Collections.Immutable.ImmutableList<global::Omnius.Core.RocketPack.Utf8String>? X24 { get; }
    public global::System.Collections.Immutable.ImmutableDictionary<byte, global::Omnius.Core.RocketPack.Utf8String>? X25 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.StructElement? X26 { get; }
    public global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? X27 { get; }

    public static bool operator ==(global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage? left, global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage? right)
    {
        return (right is null) ? (left is null) : right.Equals(left);
    }
    public static bool operator !=(global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage? left, global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage? right)
    {
        return !(left == right);
    }
    public override bool Equals(object? other)
    {
        if (other is not global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage) return false;
        return this.Equals((global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage)other);
    }
    public override bool Equals(global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage? target)
    {
        if (target is null) return false;
        if (object.ReferenceEquals(this, target)) return true;
        if (this.X0 != target.X0) return false;
        if (this.X1 != target.X1) return false;
        if (this.X2 != target.X2) return false;
        if (this.X3 != target.X3) return false;
        if (this.X4 != target.X4) return false;
        if (this.X5 != target.X5) return false;
        if (this.X6 != target.X6) return false;
        if (this.X7 != target.X7) return false;
        if (this.X8 != target.X8) return false;
        if (this.X9 != target.X9) return false;
        if (this.X10 != target.X10) return false;
        if (this.X11 != target.X11) return false;
        if (this.X12 != target.X12) return false;
        if (this.X13 != target.X13) return false;
        if (this.X14 != target.X14) return false;
        if (this.X15 != target.X15) return false;
        if (this.X16 != target.X16) return false;
        if (this.X17 != target.X17) return false;
        if (this.X18 != target.X18) return false;
        if (this.X19 != target.X19) return false;
        if (this.X20 != target.X20) return false;
        if (this.X21 != target.X21) return false;
        if ((this.X22 is null) != (target.X22 is null)) return false;
        if ((this.X22 is not null) && (target.X22 is not null) && !global::Omnius.Core.Base.BytesOperations.Equals(this.X22.Value.Span, target.X22.Value.Span)) return false;
        if ((this.X23 is null) != (target.X23 is null)) return false;
        if ((this.X23 is not null) && (target.X23 is not null) && !global::Omnius.Core.Base.BytesOperations.Equals(this.X23.Memory.Span, target.X23.Memory.Span)) return false;
        if ((this.X24 is null) != (target.X24 is null)) return false;
        if ((this.X24 is not null) && (target.X24 is not null) && !global::Omnius.Core.Base.Helpers.CollectionHelper.Equals(this.X24, target.X24)) return false;
        if ((this.X25 is null) != (target.X25 is null)) return false;
        if ((this.X25 is not null) && (target.X25 is not null) && !global::Omnius.Core.Base.Helpers.CollectionHelper.Equals(this.X25, target.X25)) return false;
        if ((this.X26 is null) != (target.X26 is null)) return false;
        if ((this.X26 is not null) && (target.X26 is not null) && this.X26 != target.X26) return false;
        if ((this.X27 is null) != (target.X27 is null)) return false;
        if ((this.X27 is not null) && (target.X27 is not null) && this.X27 != target.X27) return false;

        return true;
    }
    public override int GetHashCode() => ___hashCode.Value;

    private sealed class ___CustomSerializer : global::Omnius.Core.RocketPack.IRocketMessageSerializer<global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage>
    {
        public void Serialize(ref global::Omnius.Core.RocketPack.RocketMessageWriter w, scoped in global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage value, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            if (value.X0 != null)
            {
                w.Put((uint)1);
                w.Put(value.X0.Value);
            }
            if (value.X1 != null)
            {
                w.Put((uint)2);
                w.Put(value.X1.Value);
            }
            if (value.X2 != null)
            {
                w.Put((uint)3);
                w.Put(value.X2.Value);
            }
            if (value.X3 != null)
            {
                w.Put((uint)4);
                w.Put(value.X3.Value);
            }
            if (value.X4 != null)
            {
                w.Put((uint)5);
                w.Put(value.X4.Value);
            }
            if (value.X5 != null)
            {
                w.Put((uint)6);
                w.Put(value.X5.Value);
            }
            if (value.X6 != null)
            {
                w.Put((uint)7);
                w.Put(value.X6.Value);
            }
            if (value.X7 != null)
            {
                w.Put((uint)8);
                w.Put(value.X7.Value);
            }
            if (value.X8 != null)
            {
                w.Put((uint)9);
                w.Put(value.X8.Value);
            }
            if (value.X9 != null)
            {
                w.Put((uint)10);
                w.Put((long)value.X9);
            }
            if (value.X10 != null)
            {
                w.Put((uint)11);
                w.Put((long)value.X10);
            }
            if (value.X11 != null)
            {
                w.Put((uint)12);
                w.Put((long)value.X11);
            }
            if (value.X12 != null)
            {
                w.Put((uint)13);
                w.Put((long)value.X12);
            }
            if (value.X13 != null)
            {
                w.Put((uint)14);
                w.Put((ulong)value.X13);
            }
            if (value.X14 != null)
            {
                w.Put((uint)15);
                w.Put((ulong)value.X14);
            }
            if (value.X15 != null)
            {
                w.Put((uint)16);
                w.Put((ulong)value.X15);
            }
            if (value.X16 != null)
            {
                w.Put((uint)17);
                w.Put((ulong)value.X16);
            }
            if (value.X17 != null)
            {
                w.Put((uint)18);
                w.Put(value.X17.Value);
            }
            if (value.X18 != null)
            {
                w.Put((uint)19);
                w.Put(value.X18.Value);
            }
            if (value.X19 != null)
            {
                w.Put((uint)20);
                w.Put(value.X19);
            }
            if (value.X20 != null)
            {
                w.Put((uint)21);
                w.Put(value.X20.Value);
            }
            if (value.X21 != null)
            {
                w.Put((uint)22);
                w.Put(value.X21.Value);
            }
            if (value.X22 != null)
            {
                w.Put((uint)23);
                w.Put(value.X22.Value.Span);
            }
            if (value.X23 != null)
            {
                w.Put((uint)24);
                w.Put(value.X23.Memory.Span);
            }
            if (value.X24 != null)
            {
                w.Put((uint)25);
                w.Put((uint)value.X24.Count);
                foreach (var n in value.X24)
                {
                    w.Put(n);
                }
            }
            if (value.X25 != null)
            {
                w.Put((uint)26);
                w.Put((uint)value.X25.Count);
                foreach (var n in value.X25)
                {
                    w.Put(n.Key);
                    w.Put(n.Value);
                }
            }
            if (value.X26 != null)
            {
                w.Put((uint)27);
                global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Formatter.Serialize(ref w, value.X26, depth + 1);
            }
            if (value.X27 != null)
            {
                w.Put((uint)28);
                global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Formatter.Serialize(ref w, value.X27, depth + 1);
            }
            w.Put((uint)0);
        }
        public global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage Deserialize(ref global::Omnius.Core.RocketPack.RocketMessageReader r, scoped in int depth)
        {
            if (depth > 256) throw new global::System.FormatException();

            bool? p_x0 = null;
            sbyte? p_x1 = null;
            short? p_x2 = null;
            int? p_x3 = null;
            long? p_x4 = null;
            byte? p_x5 = null;
            ushort? p_x6 = null;
            uint? p_x7 = null;
            ulong? p_x8 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum1? p_x9 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum2? p_x10 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum3? p_x11 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum4? p_x12 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum5? p_x13 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum6? p_x14 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum7? p_x15 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.Enum8? p_x16 = null;
            float? p_x17 = null;
            double? p_x18 = null;
            global::Omnius.Core.RocketPack.Utf8String? p_x19 = null;
            global::Omnius.Core.RocketPack.Timestamp64? p_x20 = null;
            global::Omnius.Core.RocketPack.Timestamp96? p_x21 = null;
            global::System.ReadOnlyMemory<byte>? p_x22 = null;
            global::System.Buffers.IMemoryOwner<byte>? p_x23 = null;
            global::Omnius.Core.RocketPack.Utf8String[]? p_x24 = null;
            global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>? p_x25 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.StructElement? p_x26 = null;
            global::Omnius.Core.RocketPack.Tests.Internal.MessageElement? p_x27 = null;

            for (; ; )
            {
                uint id = r.GetUInt32();
                if (id == 0) break;
                switch (id)
                {
                    case 1:
                        {
                            p_x0 = r.GetBoolean();
                            break;
                        }
                    case 2:
                        {
                            p_x1 = r.GetInt8();
                            break;
                        }
                    case 3:
                        {
                            p_x2 = r.GetInt16();
                            break;
                        }
                    case 4:
                        {
                            p_x3 = r.GetInt32();
                            break;
                        }
                    case 5:
                        {
                            p_x4 = r.GetInt64();
                            break;
                        }
                    case 6:
                        {
                            p_x5 = r.GetUInt8();
                            break;
                        }
                    case 7:
                        {
                            p_x6 = r.GetUInt16();
                            break;
                        }
                    case 8:
                        {
                            p_x7 = r.GetUInt32();
                            break;
                        }
                    case 9:
                        {
                            p_x8 = r.GetUInt64();
                            break;
                        }
                    case 10:
                        {
                            p_x9 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum1)r.GetInt64();
                            break;
                        }
                    case 11:
                        {
                            p_x10 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum2)r.GetInt64();
                            break;
                        }
                    case 12:
                        {
                            p_x11 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum3)r.GetInt64();
                            break;
                        }
                    case 13:
                        {
                            p_x12 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum4)r.GetInt64();
                            break;
                        }
                    case 14:
                        {
                            p_x13 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum5)r.GetUInt64();
                            break;
                        }
                    case 15:
                        {
                            p_x14 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum6)r.GetUInt64();
                            break;
                        }
                    case 16:
                        {
                            p_x15 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum7)r.GetUInt64();
                            break;
                        }
                    case 17:
                        {
                            p_x16 = (global::Omnius.Core.RocketPack.Tests.Internal.Enum8)r.GetUInt64();
                            break;
                        }
                    case 18:
                        {
                            p_x17 = r.GetFloat32();
                            break;
                        }
                    case 19:
                        {
                            p_x18 = r.GetFloat64();
                            break;
                        }
                    case 20:
                        {
                            p_x19 = r.GetString(128);
                            break;
                        }
                    case 21:
                        {
                            p_x20 = r.GetTimestamp64();
                            break;
                        }
                    case 22:
                        {
                            p_x21 = r.GetTimestamp96();
                            break;
                        }
                    case 23:
                        {
                            p_x22 = r.GetMemory(256);
                            break;
                        }
                    case 24:
                        {
                            p_x23 = r.GetRecyclableMemory(256);
                            break;
                        }
                    case 25:
                        {
                            var length = r.GetUInt32();
                            p_x24 = new global::Omnius.Core.RocketPack.Utf8String[length];
                            for (int i = 0; i < p_x24.Length; i++)
                            {
                                p_x24[i] = r.GetString(128);
                            }
                            break;
                        }
                    case 26:
                        {
                            var length = r.GetUInt32();
                            p_x25 = new global::System.Collections.Generic.Dictionary<byte, global::Omnius.Core.RocketPack.Utf8String>();
                            byte t_key = 0;
                            global::Omnius.Core.RocketPack.Utf8String t_value = global::Omnius.Core.RocketPack.Utf8String.Empty;
                            for (int i = 0; i < length; i++)
                            {
                                t_key = r.GetUInt8();
                                t_value = r.GetString(128);
                                p_x25[t_key] = t_value;
                            }
                            break;
                        }
                    case 27:
                        {
                            p_x26 = global::Omnius.Core.RocketPack.Tests.Internal.StructElement.Formatter.Deserialize(ref r, depth + 1);
                            break;
                        }
                    case 28:
                        {
                            p_x27 = global::Omnius.Core.RocketPack.Tests.Internal.MessageElement.Formatter.Deserialize(ref r, depth + 1);
                            break;
                        }
                }
            }

            return new global::Omnius.Core.RocketPack.Tests.Internal.NullableMessage(p_x0, p_x1, p_x2, p_x3, p_x4, p_x5, p_x6, p_x7, p_x8, p_x9, p_x10, p_x11, p_x12, p_x13, p_x14, p_x15, p_x16, p_x17, p_x18, p_x19, p_x20, p_x21, p_x22, p_x23, p_x24, p_x25, p_x26, p_x27);
        }
    }
}
