name: test

on:
  push:
    branches:
      - "main"
      - "releases/*"
    paths:
      - "**"
      - "!docs/**"
      - "!**.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  StableTest: true
  # ContinuousIntegrationBuild: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install dependencies (lib)
        if: runner.os == 'Linux'
        run: sudo apt-get install libsnappy-dev

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x

      - name: Setup dotnet tool
        run: dotnet tool restore

      - name: Install dependencies
        run: dotnet restore

      - name: format check
        if: runner.os != 'Windows'
        run: dotnet format --verify-no-changes

      - name: Test
        run: dotnet test --no-restore
