name: Test

on:
  push:
    branches:
      - "**"

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      ContinuousIntegrationBuild: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Setup dotnet tool
        run: dotnet tool restore
      - name: Install dependencies
        run: dotnet restore
      - name: format check
        run: dotnet format --verify-no-changes
      - name: Test
        run: dotnet test
  windows:
    runs-on: windows-latest
    env:
      ContinuousIntegrationBuild: true
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test
